### ISSUE TITLE
[Rio de Janeiro - RJ] Desenvolvedora FullStack Pleno na IBM

### ISSUE THREAD

**Issue by Mariaaugustatorres** [minas-ti/vagas#17]
Desenvolvimento de aplicações

325496BR - [ibm.biz/AppDevs_RJ](url)

Seu papel e responsabilidades

A área de CIO da IBM está com posições abertas para que a área de desenvolvimento de softwares na criação soluções de alto valor usando as ferramentas e tecnologias mais recentes disponíveis para fornecer softwares de ponta. Estamos procurando profissionais apaixonados e qualificados, com experiência nas melhores práticas relacionadas ao desenvolvimento e teste de aplicativos.

Responsabilidades:
- Trabalhar em aplicativos existentes e novos, com inovação e valor agregado;
- Colaboração em uma equipe técnica (Squad) e com a liderança;
- Projeto e implementação de testes;
- Aproveitamento das nossas estruturas de automação de teste e contribuindo para o aumento da capacidade de automação;
- Participação no squad e contribuição no processo de planejamento de sprints / iterações e retrospectivas (ou seja, práticas ágeis).

Introdução

Conduza a IBM ao futuro, traduzindo os requisitos do sistema para o design e desenvolvimento de sistemas customizados em um ambiente ágil.  O sucesso da IBM está em suas mãos à medida que você transforma necessidades vitais de negócios em código e impulsiona a inovação. Seu trabalho potencializará a IBM e seus clientes globalmente, colaborando e integrando código em sistemas corporativos. Você terá acesso à educação, ferramentas e tecnologia mais recentes e a um plano de carreira ilimitado com o líder de tecnologia mundial.  Venha para a IBM e gere um impacto global!

Profissional Requerido e Conhecimento Técnico

Cursando graduação em Ciência da Computação ou Equivalente;
- Experiência prática em desenvolvimento de software utilizando as linguagens de programação: NodeJS, Python e / ou Java;
- Implementação prática de ferramentas de automação de teste (jUnit, Selenium, Mocha, Chai, Jasmine, Jest);
- Experiência em trabalhar com bancos de dados baseados em SQL e NoSQL (DB2, IBM Cloudant, MySQL, Mongo, CouchDB, etc);
- Experiência em trabalhar com linguagens de front-end como JavaScript, Vuejs, React, HTML, CSS / SASS;
- Experiência com sistemas de controle de fonte baseados no GitHub;
- Inglês - avançado.

Essa vaga se aplica a pessoas com deficiência ou reabilitadas,
 

Profissional Preferencial e Conhecimento Técnico

Conhecimento de nuvem (IBM Cloud, AWS, Azure, etc);
- React, Vuejs, Angular.js;
- Kubernetes, OpenShift, IBM Cirrus Platform; ---- SE PARA PLATAFORMA IBM CIRRUS EXTERNA E PUXADA
- DevOps (Jenkins, Travis, New Relic, Prometheus etc);
- APIs, arquitetura de microsserviços;
- Conhecimento em práticas de engenharia de software, incluindo técnicas ágeis;
- inglês: fluente

Educação requerida

Diploma/GED de Ensino Médio

Educação preferencial

Diploma/GED de Ensino Médio

Requisitos de elegibilidade

Todas as nossas vagas são elegíveis para pessoas com deficiência ou reabilitada

**Comment by skempfer** [comment]
Você tem algum contato via e-mail ou é somente pelo site a aplicação?

**Comment by Mariaaugustatorres** [comment]
A aplicação é pelo site ! boa sorte!!

**Comment by Mariaaugustatorres** [comment]
vaga fechada
